# Production Configuration
# Optimized for production use with enhanced safety and reliability

ollama:
  endpoint: "http://localhost:11434"
  model: "mistral:7b-instruct"
  temperature: 0.1
  max_tokens: 1000
  timeout: 45               # Slightly longer timeout for reliability
  retry_attempts: 5         # More retries for reliability
  retry_delay: 3            # Longer delay between retries

backup:
  enabled: true
  directory: "./backups"
  retention_count: 50       # Keep more backups in production
  timestamp_format: "%Y%m%d_%H%M%S"
  auto_backup: true

safety:
  max_rows_per_operation: 25    # Conservative limits for production
  max_columns_per_operation: 15 # Conservative limits for production
  dangerous_commands_blocked: true
  confirmation_required_for_deletes: true

excel:
  supported_formats: [".xlsx", ".xls", ".csv"]
  default_sheet_name: "Sheet1"
  auto_detect_headers: true
  auto_detect_data_types: true

logging:
  level: "INFO"             # Standard logging level
  file: "./logs/excel_llm.log"
  max_file_size: "25MB"     # Larger log files for production
  backup_count: 15          # Keep more log history